version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3
        environment:
          NODE_ENV: test
          DB_USER: postgres
          DB_PASS: ""
          DB_HOST: localhost
          DB_PORT: 5432
          DB_TEST: circleci_test

      - image: circleci/postgres:9.6.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: circleci_test

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn

      - run: yarn test
