version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.3
        environment:
          NODE_ENV: test
          DB_USER: postgres
          DB_PASS: ""
          DB_HOST: localhost
          DB_PORT: 5432
          DB_TEST: circleci_test

      - image: circleci/postgres:9.6.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: circleci_test

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn

      - run: yarn test

  deploy:
    docker:
      - image: node:9.3
        environment:
          NODE_ENV: production

    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh

      - add_ssh_keys:
          fingerprints:
            - "8b:48:5e:67:0e:c9:16:47:32:f2:87:0c:1f:c8:60:ad"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku restart

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
